#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

git clone https://github.com/projectatomic/docker-storage-setup.git \
    -b v0.5 /tmp/docker-storage-setup
pushd /tmp/docker-storage-setup
make install
popd
rm -rf /tmp/docker-storage-setup
